### ISSUE TITLE
How can I send a POS Tagger?

### ISSUE THREAD

**Issue by wannaphong** [UniversalDependencies/UD_Thai-PUD#1]
Hello.
How can I send a POS Tagger?
I know [RDRPOSTagger](http://rdrpostagger.sourceforge.net/) . I need to prepare the information and how to modify the data for Universal Dependencies POS Tagger?
I am sorry to ask this question because I read the document than I do not understand.
Thank you.

**Comment by dan-zeman** [comment]
Hi @wannaphongcom, I do not understand what you mean by sending a POS tagger. You can use the data in the repository to train a POS tagger, although the data is rather small and it would be better to train a tagger on a larger corpus.
